# Generated by Django 5.1.2 on 2025-02-08 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_customer_address_customer_city_customer_phone_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='state',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='zipcode',
        ),
    ]
